language: python
python:
  - '2.7'
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: rjosephwright
    password:
      secure: c3nWhcsc20Z7SaV+UjDpwguEqjHGG7ANhv6EpaKxvgd/aMpvgn/5nGraOsYagGEHdp9UQE1v5z3KkDXib/u/3Y7anTdI90TaDieFVbfTyXIki9qeFoN5XoOcZuPx/w7YK/ZSM/SBVWxbRByNwbX76JHFdxrycTJyoPwalTLGXt0nzt6t6NsE3bmrhfVzjNwfZi79SkpJ9hsw6sfNPKOR//2aTO3WkUjIFSFKfA25xbNQp7vlHCXJTDlIsDVXBzwq0yjXJcXj5lRRVEGf9Den2k14xq6O/wd8LB1xiM5noRT5t4Aa2uhjU9daY1k5Sjr37OhRAs5VZKNESLHWh2okIH/I+Z0WSCcmGyviHwn5ofEZsKH0VlUVzn8DHu6KQPPE/tKcQ6GkIHjgFA7Bxk22QBiQVJTC/QNGk4njcWmWEI2tBAy9WFaWtLS1e1fVveixuSfeHZcS16gdQ20nNaAvGEDIN6K3JoLYiSfBNTBf6cFFEwgkOEeGTiInaOMdWt5NF8bVnzBQ2cYXxC3Dvi6R10UH8E4eg+6gUchLgbvCT5rUhxU4J/+q2DnEFTZFpiYCJuD/N2F9MUUfbXiEMwJSok1U6ajyzTcQKy8E+oWVVxXMxf14acLjmpJPQBzoxgVLgYNkZ4sHhlX3cIfgliaw64wT0xHa5P00opIRs9lUkxQ=
    on:
      tags: true
    distributions: sdist bdist_wheel
