language: python
python:
  - '2.7'
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: rjosephwright
    password:
      secure: 'tsS80WyA18eRn2poWAo9H/UEvKmsqv27WYEKnUjeuzQb/wwPS+gaU8cB6BazI8TczZUbdOpS2vRC3OgSUV7hQkKl1udGjPHLJJ5Qett1qEatjohqNAgajUoF3929wp5ebWSjl3KQAJt/7kRiVUMAz9eci9Hzy1C1RI/ED2yC5VEEnTmT7h20ZV4+d5vqVbJs9SLW1wR7HU/RAG913VoL4MrtgraeKeVIqEUlPTW368ZwtotwiVwU3j0ceHeYpObqCuKcYzw9TMJXmpz6CFZE4pWO2eU9Yo9AX0ZkDQKzOkmD1JUGf58Ayi1d5MlBYPvaDklx6AXMFkZuOtNaqtNGplI8P1uKLq3c0wv4D5cuewGPmYpARNdFQKmP8DAnpfYIyLBHboH/5CZalCJQpaoKhTU2C2oJNvl1YAaJFASGED5vGxLEsavQrGi+2u1Sg7HYPmfaYWKUAvlXMRnPqRqgfCtlLWQQNjVt/lWGskwr2og5xhKpVOnknuCayL9jdm/ADslrukH6b+yOsd1OyzyXXT5YN/rbCmhVLgJknKKCzZ1nefNXhG8/FRSXu/dzwcDbnh7MKEjgQIXmouHG0dYPkxueRsrJk97RcsJW29NVl0tRM5j5V3/Ls9J6LaWAp6kDYLkgO1EVZUrQW2gWWHnc+LuC5sNLHz8LIPNBpEjMF9U='
    on:
      tags: true
    distributions: sdist bdist_wheel
    repo: cloudboss/friend
